### ISSUE TITLE
Use Automatic Session Management

### ISSUE THREAD

**Issue by f2prateek** [segment-integrations/analytics-android-integration-localytics#1]
Since we don't support <14 anyway - http://docs.localytics.com/dev/android.html

**Comment by hankim813** [comment]
@f2prateek not sure if this is still a valid issue? if so could you add to jira and close this issue?

**Comment by brennan** [comment]
Added this to JIRA: https://segment.atlassian.net/browse/PLATFORM-1857 - closing issue here.
