### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by marcellogalhardo** [segment-integrations/analytics-android-integration-localytics#11]
I'm trying to migrate to AndroidX and we use this library in our project. However, this is currently causing an issue in our project:

> Unable to resolve dependency for ':module@buildType/compileClasspath': Failed to transform file 'localytics-1.3.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform

Removing the library makes this issue disappear.
Is there any workaround that would allow me to migrate to AndroidX til this library is migrated?

Thank you.

**Comment by f2prateek** [comment]
This question is probably better suited to ask Localytics directly as the error originates from their Library. I suspect you'll run into this issue if you were not using Segment and using Localytics directly.

You could also try experimenting with setting  `android.enableJetifier=false`.

**Comment by marcellogalhardoquandoo** [comment]
@f2prateek I believe my issue is related to this library because when I remove the following line: `implement "com.segment.analytics.android.integrations:localytics:1.3.0"`, it works. Though, I will ask on Localytics as well (the enableJetifier is necessary for some other libraries so I can't turn it off in the project...).

**Comment by marcellogalhardo** [comment]
@f2prateek I thought my issue was related to this library because when I remove the following line: `implement "com.segment.analytics.android.integrations:localytics:1.3.0"`, it works. Though, I will ask on Localytics as well (the enableJetifier is necessary for some other libraries so I can't turn it off in the project...).

**Comment by f2prateek** [comment]
> I thought my issue was related to this library because when I remove the following line: implement "com.segment.analytics.android.integrations:localytics:1.3.0", it works.

Yes - but that's because this library depends on the Localytics library.

If you add the localities dependency directly (like this https://github.com/segment-integrations/analytics-android-integration-localytics/blob/master/build.gradle#L45), you'll likely see the same error

**Comment by marcellogalhardo** [comment]
Ahhh, clear! Thank you very much. 👍
